DROP TABLE IF EXISTS `cat` CASCADE;

CREATE TABLE `cat` (
	`id` INTEGER PRIMARY KEY AUTO_INCREMENT,
	`name` VARCHAR(255) NOT NULL, 
	`age` INTEGER, 
	`colour` VARCHAR(255) NOT NULL, 
	`is_cute` BOOLEAN
);